### PR TITLE
Finished challenges and added images

### PR DESCRIPTION
**Pull request by badriyahs**

### CODE REVIEW

**Comment by dantaeyoung** [comment]
Hi @badriyahs ! Your folder looks good, but it looks like you might have deleted the files in the folder dan_copy_me_and_rename -- would you be able to restore those files and submit another pull request?

**Comment by badriyahs** [comment]
@dantaeyoung oops sorry! i'm not sure how to put it back, i'll figure it out asap!

**Comment by badriyahs** [comment]
hi @dantaeyoung , does this pull request need to be approved before i add on more assignment images? thank you!

**Comment by badriyahs** [comment]
Added Week06 practice and stepper motor tutorials

**Review by dantaeyoung — COMMENTED** [review]
Great work! Moving files to student_work and student_practice directory.

**Pull request merged**
